apiVersion: v1
kind: Service
metadata:
  name: {{ include "fiap-hackathon-worker.fullname" . }}
  labels:
    {{- include "fiap-hackathon-worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: 'http'
  selector:
    {{- include "fiap-hackathon-worker.selectorLabels" . | nindent 4 }}